load('ce461_FINAL_KaanTan_2162824')%getting global variables from the main .m file
fprintf("This report has been generated by SinglePileCapacityCalculator v1.0 on " + date)
fprintf("\nThe soil properties and pile dimensions used in calculations are provided below\n\n")


for step = 1:number_layer%naming of layers are created and stored in the title cell
        layer_titles = "Layer " + string(step);
        exported_title{step+1} = char(layer_titles);
end
    exported_title{1} = 'Property'; %title's first column's string is written

    exported_data = cell(8,number_layer+1); %preallocation
    exported_data(:,1) = {'Type';'Start';'End';'satUW';'Cu';'adhFact';'phiAngle';'Nq'}; %first column data
for layer = 1:number_layer %other columns' data are defined and stored respectively
        exported_data(:,layer+1) = {data_cell_soil_type(layer,1);
                                    data_cell_values(layer,1);
                                    data_cell_values(layer,2);
                                    data_cell_values(layer,3);
                                    data_cell_values(layer,4);
                                    data_cell_values(layer,5);
                                    data_cell_values(layer,6);
                                    data_cell_values(layer,7);};
                                    
end
result = cell2table(exported_data); %all cell elements are turned into a table column by column
result.Properties.VariableNames = exported_title; %title is changed
disp(result)

fprintf("\nPile Diameter (m):\n\t" + string(diameter_pile))
fprintf("\nPile Length (m):\n\t" + string(length_pile))
fprintf("\n\nSkin Friction (kN):\n\t");fprintf(Qs);
fprintf("\nTip Resistance (kN):\n\t");fprintf(Qp);
fprintf("\nUltimate Capacity (kN):\n\t");fprintf(Qult);
